### ISSUE TITLE
REquisitos

### ISSUE THREAD

**Issue by JorgeArroyo33** [JorgeArroyo33/Pruebas-Iso#4]

**Comment by SergiooCoorne** [comment]
No me sale de los huevos hacer la tarea

**Comment by JorgeArroyo33** [comment]
pues la haces gilipollas

**Comment by SergiooCoorne** [comment]
Te voy a dar de ostias puto anormal

**Comment by SergiooCoorne** [comment]
Y la cierro porque me sale de los huevos, soy el jefe
